// src/localization.js

import { state } from './state.js';

export const TRANSLATIONS = {
  en: {
    gameTitle: "Closer to the sun ☼",
    newGame: "New Game",
    endlessMode: "Endless Mode",
    continueGame: "Continue",
    settings: "Settings",
    credits: "Credits",
    versionText: "Closer to the sun remake - v1.0",
    music: "Music",
    sounds: "Sounds",
    fullscreen: "Fullscreen",
    close: "Close",
    exit: "Exit",
    craft: "Craft",
    equipped: "Equipped:",
    none: "None",
    distance: "Distance",
    tier: "Tier",
    speed: "Speed",
    durability: "Durability",
    buyPrice: "Buy Price: 1 Coin",
    sellValue: "Sell Value: 1 Coin",
    clickToBuy: "Click to BUY",
    clickToSell: "Click to SELL",
    owned: "Owned:",
    outOfStamina: "OUT OF STAMINA!",
    falling: "FALLING!",
    selectLanguage: "SELECT LANGUAGE",
    selectControls: "SELECT CONTROL TYPE",
    controls: "Controls",
    keyboardControls: "Keyboard & Mouse",
    touchControls: "Touch Screen",
    btnFlap: "FLAP",
    btnAction: "INTERACT",
    pauseTitle: "PAUSE",
    resume: "Resume",
    mainMenu: "Main Menu",
    promptContinue: "Press E to continue",
    
    promptTower: "Press E - Head to the Tower",
    promptWorkshop: "Press E - Open Workshop",
    promptShop: "Press E - Open Merchant Shop",
    promptVillager: "Press E - Talk to Dummy",
    promptSalesman: "Press E - Talk to Merchant",
    promptBum: "Press E - Talk to Drunkard",
    promptReturnCity: "[T] Return to Town",

    promptTowerTouch: "TAP INTERACT - Head to Tower",
    promptWorkshopTouch: "TAP INTERACT - Open Workshop",
    promptShopTouch: "TAP INTERACT - Open Shop",
    promptVillagerTouch: "TAP INTERACT - Talk to Dummy",
    promptSalesmanTouch: "TAP INTERACT - Talk to Merchant",
    promptBumTouch: "TAP INTERACT - Talk to Drunkard",

    promptCutsceneStart: "Press any key or TAP to continue",
    promptCutsceneFlap: "Press Space or TAP to fly",
    skipHintTouch: "TAP HERE to Skip",
    
    loading: "Loading...",
    defeatMessage: "Daedalus fell and is returning to the city",
    cutsceneWingsText: "I need stronger wings...",
    droneWarning: "You feel like someone is following you...",
    droneEscaped: "It seems it fell behind...",

    retryPrompt: "Try again?",
    retryYes: "Yes",
    retryNo: "No",

    runSummaryTitle: "RUN SUMMARY",
    summaryDistance: "Distance Reached",
    summaryTime: "Flight Time",
    summaryLoot: "Collected Items",
    nothingCollected: "Nothing gathered this time...",
    continueBtn: "CONTINUE",

    thankYouForPlaying: "Thank you for playing!",
    endingTheEnd: "THE END",

    developerNoteTitle: "From the developer:",
    developerNoteBody: "I doubt this setback will stop Daedalus from climbing the tower further. Thank you so much for playing our game!\nEndless Mode Unlocked.",

    clearSave: "Reset Progress",
    clearSaveConfirm: "Are you sure you want to delete all saved data?",

    endingSentence1: "In the veiled dawn of forgotten legends, the Tower was whispered to bear some sacred purpose — that ancient delusion now lies shattered into dust.",
    endingSentence2: "It rises instead as the raw, throbbing embodiment of human will alone.",

    npc_daedalus: "Daedalus",
    npc_salesman: "Merchant",
    npc_dummy: "Dummy",

    dialogueIntro: "I should stop by the workshop and try to make some stronger wings. Maybe I'll take a walk around town while I'm at it.",
    dialogueNeedWings: "I need to craft new wings first!",
    dialogueNpc1_1: "Hello craftsman, how are you?",
    dialogueNpc1_2: "It could have been better",
    dialogueNpc1_3: "You're still young, but don't forget to come home from this tower of yours",
    dialogueNpc1_4: "Of course, take care",
    dialogueNpc2_1: "I think your wings are funny",
    dialogueNpc2_2: "With better wings you can HOLD space to fly higher!",
    dialogueNpc2_3: "What I just said? Never mind. I think I've seen purple cube in the forest",
    dialogueBum_1: "*Hic!* ... *Hic!*",
    dialogueBum_2: "He reeks of alcohol...",

    tutorialTitle: "CONTROLS & GUIDE",
    tutorialCityTitle: "In Town",
    tutorialCityText: "A / D — Walk around<br/>E — Interact with NPCs & Shops",
    tutorialCityTextTouch: "◄ / ► — Walk around<br/>INTERACT — Talk & Open Shops",
    tutorialTowerTitle: "In Tower",
    tutorialTowerText: "SPACE — Flap & Fly higher<br/>A / D — Rotate around Tower",
    tutorialTowerTextTouch: "FLAP — Fly & Jump higher<br/>◄ / ► — Rotate around Tower",
    tutorialBtn: "GOT IT!",

    introSlide1: "Game by Dahaton and Coyz<br/><br/>Music:<br/>A Long Story by Damiano Baldoni",
    introSlide2: "The legend says people of the past have built a tower.",
    introSlide3: "Tower so tall one couldn't even see its peak.",
    introSlide4: "Its purpose is unknown to this very day.",
    introSlide5: "And every day to come.",
    introSlide6: "Or so it says.",

    creditsTitle: "CREDITS",
    gameCreatedBy: "Game Created By:",
    authorsList: "Dahaton & Coyz",
    musicBy: "Music:",
    musicianName: "Damiano Baldoni",
    specialThanks: "Special thanks to all testers and players!",
    
    lockedRecipe: "Locked - Reach higher Tier in Tower",
    climbToDiscover: "Climb the Tower to discover!",
    shopHint: "Click to buy / sell. Press [E] to exit",

    item_fabric1: "Fabric I", item_fabric2: "Fabric II", item_fabric3: "Fabric III",
    item_steel1: "Steel I", item_steel2: "Steel II", item_steel3: "Steel III",
    item_wood1: "Wood I", item_wood2: "Wood II", item_wood3: "Wood III",
    item_wax: "Wax", item_coin: "Coin",

    wing_SteelWings: "Steel Wings",
    wing_DurableSteelWings: "Durable Steel Wings",
    wing_SuperSteelWings: "Super Steel Wings",
    wing_SuperDurableSteelWings: "Super Durable Steel Wings",
    wing_EnchantedWings: "Enchanted Wings",
    wing_DurableEnchantedWings: "Durable Enchanted Wings",
    wing_SuperEnchantedWings: "Super Enchanted Wings",
    wing_SuperDurableEnchantedWings: "Durable Super Enchanted Wings",
    wing_MythrilWings: "Mythril Wings",
    wing_DurableMythrilWings: "Durable Mythril Wings",
    wing_WaxWings: "Wax Wings"
  },
  be: {
    gameTitle: "Closer to the sun ☼",
    newGame: "Новая гульня",
    endlessMode: "Бясконцы рэжым",
    continueGame: "Працягнуць",
    settings: "Налады",
    credits: "Аўтары",
    versionText: "Closer to the sun remake - v1.0",
    music: "Музыка",
    sounds: "Гукі",
    fullscreen: "Поўны экран",
    close: "Зачыніць",
    exit: "Выхад",
    craft: "Стварыць",
    equipped: "Экіпіравана:",
    none: "Няма",
    distance: "Адлегласць",
    tier: "Узровень",
    speed: "Хуткасць",
    durability: "Трываласць",
    buyPrice: "Цана куплі: 1 манета",
    sellValue: "Цана продажу: 1 манета",
    clickToBuy: "Націсніце, каб КУПІЦЬ",
    clickToSell: "Націсніце, каб ПРАДАЦЬ",
    owned: "У наяўнасці:",
    outOfStamina: "СКОНЧЫЛАСЯ ВЫНОСЛІВАСЦЬ!",
    falling: "ПАДЗЕННЕ!",
    selectLanguage: "ВЫБЕРЫЦЕ МОВУ",
    selectControls: "ВЫБЕРЫЦЕ КІРАВАННЕ",
    controls: "Кіраванне",
    keyboardControls: "Клавіятура і мыш",
    touchControls: "Сэнсарны экран",
    btnFlap: "УЗМАХ",
    btnAction: "ДЗЕЯННЕ",
    pauseTitle: "ПАЎЗА",
    resume: "Узнавіць",
    mainMenu: "Галоўнае меню",
    promptContinue: "Націсніце E, каб працягнуць",
    
    promptTower: "Націсніце E - Накіравацца да Вежы",
    promptWorkshop: "Націсніце E - Адкрыць Майстэрню",
    promptShop: "Націсніце E - Адкрыць Краму",
    promptVillager: "Націсніце E - Пагаварыць з Чудачкай",
    promptSalesman: "Націсніце E - Пагаварыць з гандляром",
    promptBum: "Націсніце E - Пагаварыць з П'яніцам",
    promptReturnCity: "[T] Вярнуцца ў горад",

    promptTowerTouch: "НАЦІСНІЦЕ ДЗЕЯННЕ - Да Вежы",
    promptWorkshopTouch: "НАЦІСНІЦЕ ДЗЕЯННЕ - Майстэрня",
    promptShopTouch: "НАЦІСНІЦЕ ДЗЕЯННЕ - Крама",
    promptVillagerTouch: "НАЦІСНІЦЕ ДЗЕЯННЕ - Размова з Чудачкай",
    promptSalesmanTouch: "НАЦІСНІЦЕ ДЗЕЯННЕ - Размова з Гандляром",
    promptBumTouch: "НАЦІСНІЦЕ ДЗЕЯННЕ - Размова з П'яніцам",

    promptCutsceneStart: "Націсніце або ТАПНІЦЕ, каб працягнуць",
    promptCutsceneFlap: "Націсніце прабел або ТАПНІЦЕ, каб узляцець",
    skipHintTouch: "ТАПНІЦЕ ТУТ, каб прапусціць",
    
    loading: "Загрузка...",
    defeatMessage: "Дэдал упаў і вяртаецца ў горад",
    cutsceneWingsText: "Мне патрэбны мацнейшыя крылы...",
    droneWarning: "Вы адчуваеце, што хтосьці вас пераследуе...",
    droneEscaped: "Здаецца, ён адстаў ад вас...",

    retryPrompt: "Паўтарыць спробу?",
    retryYes: "Так",
    retryNo: "Ні",

    runSummaryTitle: "ВЫНІКІ ЗАБЕГУ",
    summaryDistance: "Пройдзеная адлегласць",
    summaryTime: "Час палёту",
    summaryLoot: "Сабраныя рэчы",
    nothingCollected: "Гэтым разам нічога не сабрана...",
    continueBtn: "ПРАЦЯГНУЦЬ",

    thankYouForPlaying: "Дзякуй за гульню!",
    endingTheEnd: "КАНЕЦ",

    developerNoteTitle: "Ад распрацоўшчыка:",
    developerNoteBody: "Сумняваюся, што гэта спыніць Дэдала і далей узбірацца на вежу. Вялікі дзякуй за тое, што прайшлі нашу гульню!\nРазблакаваны бясконцы рэжым.",

    clearSave: "Скінуць прагрэс",
    clearSaveConfirm: "Вы ўпэўнены, што хочаце выдаліць усе захаваныя даныя?",

    endingSentence1: "У смузе заранкі забытых легенд пагаворвалі, што Вежа мае святую мэту — гэта старажытнае омана цяпер рассыпалася ў пыл.",
    endingSentence2: "Замест гэтага яна узвышаецца як увасабленне чалавечай волі.",

    npc_daedalus: "Дэдал",
    npc_salesman: "Гандляр",
    npc_dummy: "Чудачка",

    dialogueIntro: "Мне варта зазірнуць у майстэрню і паспрабаваць зрабіць больш моцныя крылы. А па дарозе можна прагуляцца па горадзе.",
    dialogueNeedWings: "Спачатку мне патрэбны новыя крылы!",
    dialogueNpc1_1: "Прывіт, майстра, як справы?",
    dialogueNpc1_2: "Магло б быць і лепш",
    dialogueNpc1_3: "Ты яшчэ малады, але не забывай вяртацца дадому з гэтай сваёй вежы",
    dialogueNpc1_4: "Беражы сябе",
    dialogueNpc2_1: "Мне здаецца, твае крылы забаўныя",
    dialogueNpc2_2: "З лепшымі крыламі ты можаш УТРЫМЛІВАЦЬ прабел, каб ляцець вышэй!",
    dialogueNpc2_3: "Што я толькі што сказала? Забудзь. Здаецца, я бачыла фіолетавы куб у лесе",
    dialogueBum_1: "*Ік!* ... *Ік!*",
    dialogueBum_2: "Ад яго нясе перагарам...",

    tutorialTitle: "НАВУЧАННЕ",
    tutorialCityTitle: "У горадзе",
    tutorialCityText: "A / D — Перамяшчэнне<br/>E — Узаемадзеянне",
    tutorialCityTextTouch: "◄ / ► — Перамяшчэнне<br/>ДЗЕЯННЕ — Размова і Крамы",
    tutorialTowerTitle: "У вежы",
    tutorialTowerText: "ПРАБЕЛ — Узмах крылаў<br/>A / D — Манеўраванне",
    tutorialTowerTextTouch: "УЗМАХ — Узлёт вышэй<br/>◄ / ► — Манеўраванне",
    tutorialBtn: "ЗРАЗУМЕЛА!",

    introSlide1: "Гульня ад Dahaton і Coyz<br/><br/>Музыка:<br/>A Long Story — Damiano Baldoni",
    introSlide2: "Легенда абвяшчае, што людзі мінулага пабудавалі вежу.",
    introSlide3: "Вежу настолькі высокую, што ніхто не бачыў яе вяршыні.",
    introSlide4: "Яе прызначэнне невядома і дагэтуль.",
    introSlide5: "I кожны наступны дзень.",
    introSlide6: "Прынамсі, так кажуць.",

    creditsTitle: "Аўтары",
    gameCreatedBy: "Стваральнікі гульні:",
    authorsList: "Dahaton і Coyz",
    musicBy: "Музыка:",
    musicianName: "Damiano Baldoni",
    specialThanks: "Асаблівая падзяка тэстарам і гульцам!",
    
    lockedRecipe: "Заблакавана - дасягніце вышэйшага ўзроўню ў Вежы",
    climbToDiscover: "Узбірайцеся на Вежу, каб адкрыць!",
    shopHint: "Націсніце, каб купіць / прадаць. [E] - Выход",

    item_fabric1: "Тканіна I", item_fabric2: "Тканіна II", item_fabric3: "Тканіна III",
    item_steel1: "Сталь I", item_steel2: "Сталь II", item_steel3: "Сталь III",
    item_wood1: "Дрэва I", item_wood2: "Дрэва II", item_wood3: "Дрэва III",
    item_wax: "Воск", item_coin: "Манета",

    wing_SteelWings: "Стальныя крылы",
    wing_DurableSteelWings: "Трывалыя стальныя крылы",
    wing_SuperSteelWings: "Суперстальныя крылы",
    wing_SuperDurableSteelWings: "Трывалыя суперстальныя крылы",
    wing_EnchantedWings: "Зачараваныя крылы",
    wing_DurableEnchantedWings: "Трывалыя зачараваныя крылы",
    wing_SuperEnchantedWings: "Суперзачараваныя крылы",
    wing_SuperDurableEnchantedWings: "Трывалыя суперзачараваныя крылы",
    wing_MythrilWings: "Міфрылавыя крылы",
    wing_DurableMythrilWings: "Трывалыя міфрылавыя крылы",
    wing_WaxWings: "Воскавыя крылы"
  },
  uk: {
    gameTitle: "Closer to the sun ☼",
    newGame: "Нова гра",
    endlessMode: "Нескінченний режим",
    continueGame: "Продовжити",
    settings: "Налаштування",
    credits: "Автори",
    versionText: "Closer to the sun remake - v1.0",
    music: "Музика",
    sounds: "Звуки",
    fullscreen: "Повноекранний режим",
    close: "Закрити",
    exit: "Вихід",
    craft: "Створити",
    equipped: "Екіпіровано:",
    none: "Немає",
    distance: "Дистанція",
    tier: "Рівень",
    speed: "Швидкість",
    durability: "Міцність",
    buyPrice: "Ціна купівлі: 1 монета",
    sellValue: "Ціна продажу: 1 монета",
    clickToBuy: "Натисніть, щоб КУПИТИ",
    clickToSell: "Натисніть, щоб ПРОДАТИ",
    owned: "У наявності:",
    outOfStamina: "ЗАКІНЧИЛАСЯ ВИТРИВАЛІСТЬ!",
    falling: "ПАДІННЯ!",
    selectLanguage: "ОБЕРІТЬ МОВУ",
    selectControls: "ОБЕРІТЬ КЕРУВАННЯ",
    controls: "Керування",
    keyboardControls: "Клавіатура та миша",
    touchControls: "Сенсорний екран",
    btnFlap: "ЗМАХ",
    btnAction: "ДІЯ",
    pauseTitle: "ПАУЗА",
    resume: "Відновити",
    mainMenu: "Головне меню",
    promptContinue: "Натисніть E, щоб продовжити",
    
    promptTower: "Натисніть E - Вирушити до Вежі",
    promptWorkshop: "Натисніть E - Відкрити Майстерню",
    promptShop: "Натисніть E - Відкрити Крамницю",
    promptVillager: "Натисніть E - Поговорити з Дивачкою",
    promptSalesman: "Натисніть E - Поговорити з торговцем",
    promptBum: "Натисніть E - Поговорити з п'яницею",
    promptReturnCity: "[T] Повернутися до міста",

    promptTowerTouch: "НАТИСНІТЬ ДІЮ - До Вежі",
    promptWorkshopTouch: "НАТИСНІТЬ ДІЮ - Майстерня",
    promptShopTouch: "НАТИСНІТЬ ДІЮ - Крамниця",
    promptVillagerTouch: "НАТИСНІТЬ ДІЮ - Розмова з Дивачкою",
    promptSalesmanTouch: "НАТИСНІТЬ ДІЮ - Розмова з Торговцем",
    promptBumTouch: "НАТИСНІТЬ ДІЮ - Розмова з П'яницею",

    promptCutsceneStart: "Натисніть або ТАПНІТЬ, щоб продовжити",
    promptCutsceneFlap: "Натисніть пробіл або ТАПНІТЬ, щоб злетіти",
    skipHintTouch: "ТАПНІТЬ ТУТ, щоб пропустити",
    
    loading: "Завантаження...",
    defeatMessage: "Дедал упав і повертається до міста",
    cutsceneWingsText: "Мне потрібні міцніші крила...",
    droneWarning: "Ви відчуваєте, що хтось вас переслідує...",
    droneEscaped: "Здається, він відстав від вас...",

    retryPrompt: "Спробувати ще раз?",
    retryYes: "Так",
    retryNo: "Ні",

    runSummaryTitle: "ПІДСУМКИ ЗАБІГУ",
    summaryDistance: "Пройдена дистанція",
    summaryTime: "Час польоту",
    summaryLoot: "Зібрані предметы",
    nothingCollected: "Цього разу нічого не зібрано...",
    continueBtn: "ПРОДОВЖИТИ",

    thankYouForPlaying: "Дякуємо за гру!",
    endingTheEnd: "КІНЕЦЬ",

    developerNoteTitle: "Від розробника:",
    developerNoteBody: "Сумніваюся, що це зупинить Дедала від подальшого сходження на вежу. Щиро дякуємо за те, що пройшли нашу гру!\nРозблоковано нескінченний режим.",

    clearSave: "Скинути прогрес",
    clearSaveConfirm: "Ви впевнені, що хочете видалити всі збережені дані?",

    endingSentence1: "У серпанку світанку забутих легенд подейкували, що Вежа має сакральну мету — ця стародавня омана тепер розсипалася на порох.",
    endingSentence2: "Натомість вона величніє як чисте втілення людської волі.",

    npc_daedalus: "Дедал",
    npc_salesman: "Торговець",
    npc_dummy: "Дивачка",

    dialogueIntro: "Зайду до майстерні та спробую змайструвати міцніші крила. Заоднем і містом прогуляюся.",
    dialogueNeedWings: "Спочатку мені потрібні нові крила!",
    dialogueNpc1_1: "Привіт, ремісниче, як справи?",
    dialogueNpc1_2: "Могло б бути й краще",
    dialogueNpc1_3: "Ти ще молодий, але не забудь повернутися додому з цієї сваєї вежі",
    dialogueNpc1_4: "Бережи себе",
    dialogueNpc2_1: "Твої крила кумедні",
    dialogueNpc2_2: "З кращими крилами ти можеш УТРИМУВАТИ пробіл, щоб летіти вище!",
    dialogueNpc2_3: "Що я тільки-но сказала? Неважливо. Здається, я бачила фіолетовий куб у лісі",
    dialogueBum_1: "*Ік!* ... *Ік!*",
    dialogueBum_2: "Від нього тхне перегаром...",

    tutorialTitle: "НАВЧАННЯ",
    tutorialCityTitle: "У місті",
    tutorialCityText: "A / D — Переміщення<br/>E — Взаємодія",
    tutorialCityTextTouch: "◄ / ► — Переміщення<br/>ДІЯ — Розмова та Крамниці",
    tutorialTowerTitle: "У вежі",
    tutorialTowerText: "ПРОБІЛ — Взмах крил<br/>A / D — Маневрування",
    tutorialTowerTextTouch: "ЗМАХ — Політ вище<br/>◄ / ► — Маневрування",
    tutorialBtn: "ЗРОЗУМІЛО!",

    introSlide1: "Гра від Dahaton та Coyz<br/><br/>Музика:<br/>A Long Story — Damiano Baldoni",
    introSlide2: "Легенда каже, що люди минулого збудували вежу.",
    introSlide3: "Вежу настільки високу, що ніхто не бачив її вершини.",
    introSlide4: "Її призначення невідоме й донині.",
    introSlide5: "І кожен наступний день.",
    introSlide6: "Принаймні, так кажуть.",

    creditsTitle: "АВТОРИ",
    gameCreatedBy: "Творці гри:",
    authorsList: "Dahaton та Coyz",
    musicBy: "Музика:",
    musicianName: "Damiano Baldoni",
    specialThanks: "Особлива подяка тестерам та гравцям!",
    
    lockedRecipe: "Заблоковано - досягніть вищого рівня у Вежі",
    climbToDiscover: "Піднімайтеся на Вежу, щоб відкрити!",
    shopHint: "Натисніть, щоб купити / продати. [E] - Вихід",

    item_fabric1: "Тканина I", item_fabric2: "Тканина II", item_fabric3: "Тканина III",
    item_steel1: "Сталеві I", item_steel2: "Сталь II", item_steel3: "Сталь III",
    item_wood1: "Дерево I", item_wood2: "Дерево II", item_wood3: "Дерево III",
    item_wax: "Віск", item_coin: "Монета",

    wing_SteelWings: "Сталеві крила",
    wing_DurableSteelWings: "Міцні сталеві крила",
    wing_SuperSteelWings: "Суперсталеві крила",
    wing_SuperDurableSteelWings: "Міцні суперсталеві крила",
    wing_EnchantedWings: "Зачаровані крила",
    wing_DurableEnchantedWings: "Міцні зачаровані крила",
    wing_SuperEnchantedWings: "Суперзачаровані крила",
    wing_SuperDurableEnchantedWings: "Міцні суперзачаровані крила",
    wing_MythrilWings: "Міفريлові крила",
    wing_DurableMythrilWings: "Міцні міفريлові крила",
    wing_WaxWings: "Воскові крила"
  },
  ru: {
    gameTitle: "Closer to the sun ☼",
    newGame: "Новая игра",
    endlessMode: "Бесконечный режим",
    continueGame: "Продолжить",
    settings: "Настройки",
    credits: "Авторы",
    versionText: "Closer to the sun remake - v1.0",
    music: "Музыка",
    sounds: "Звуки",
    fullscreen: "Полноэкранный режим",
    close: "Закрыть",
    exit: "Выход",
    craft: "Создать",
    equipped: "Экипировано:",
    none: "Нет",
    distance: "Дистанция",
    tier: "Уровень",
    speed: "Скорость",
    durability: "Прочность",
    buyPrice: "Цена покупки: 1 монета",
    sellValue: "Цена продажи: 1 монета",
    clickToBuy: "Нажмите, чтобы КУПИТЬ",
    clickToSell: "Нажмите, чтобы ПРОДАТЬ",
    owned: "В наличии:",
    outOfStamina: "ЗАКОНЧИЛАСЬ ВЫНОСЛИВОСТЬ!",
    falling: "ПАДЕНИЕ!",
    selectLanguage: "ВЫБЕРИТЕ ЯЗЫК",
    selectControls: "ВЫБЕРИТЕ УПРАВЛЕНИЕ",
    controls: "Управление",
    keyboardControls: "Клавиатура и мышь",
    touchControls: "Сенсорный экран",
    btnFlap: "ВЗМАХ",
    btnAction: "ДЕЙСТВИЕ",
    pauseTitle: "ПАУЗА",
    resume: "Продолжить",
    mainMenu: "Главное меню",
    promptContinue: "Нажмите E, чтобы продолжить",
    
    promptTower: "Нажмите E - Направиться к Башне",
    promptWorkshop: "Нажмите E - Открыть Мастерскую",
    promptShop: "Нажмите E - Открыть Магазин",
    promptVillager: "Нажмите E - Поговорить с Чудачкой",
    promptSalesman: "Нажмите E - Поговорить с Торговцем",
    promptBum: "Нажмите E - Поговорить с Пьяницей",
    promptReturnCity: "[T] Вернуться в город",

    promptTowerTouch: "НАЖМИТЕ ДЕЙСТВИЕ - К Башне",
    promptWorkshopTouch: "НАЖМИТЕ ДЕЙСТВИЕ - Мастерская",
    promptShopTouch: "НАЖМИТЕ ДЕЙСТВИЕ - Магазин",
    promptVillagerTouch: "НАЖМИТЕ ДЕЙСТВИЕ - Разговор с Чудачкой",
    promptSalesmanTouch: "НАЖМИТЕ ДЕЙСТВИЕ - Разговор с Торговцем",
    promptBumTouch: "НАЖМИТЕ ДЕЙСТВИЕ - Разговор с Пьяницей",

    promptCutsceneStart: "Нажмите или ТАПНИТЕ, чтобы продолжить",
    promptCutsceneFlap: "Нажмите на пробел или ТАПНИТЕ, чтобы взлететь",
    skipHintTouch: "НАЖМИТЕ СЮДА, чтобы пропустить",

    loading: "Загрузка...",
    defeatMessage: "Даэдал упал и возвращается в город",
    cutsceneWingsText: "Мне нужны крылья сильнее...",
    droneWarning: "Вы чувствуете, что вас кто-то преследует...",
    droneEscaped: "Кажется, он отстал от вас...",

    retryPrompt: "Попробовать снова?",
    retryYes: "Да",
    retryNo: "Нет",

    runSummaryTitle: "ИТОГИ ЗАБЕГА",
    summaryDistance: "Пройденная дистанция",
    summaryTime: "Время полёта",
    summaryLoot: "Собрано предметов",
    nothingCollected: "В этот раз ничего не собрано...",
    continueBtn: "ПРОДОЛЖИТЬ",

    thankYouForPlaying: "Спасибо за игру!",
    endingTheEnd: "КОНЕЦ",

    developerNoteTitle: "От разработчика:",
    developerNoteBody: "Сомневаюсь что это остановит Даэдала и дальше взбираться на башню. Спасибо большое за то что прошли нашу игру!\nРазблокирован бесконечный режим.",

    clearSave: "Сбросить прогресс",
    clearSaveConfirm: "Вы уверены, что хотите удалить все сохраненные данные?",

    endingSentence1: "В туманной дымке забытых легенд шептались, будто Башня несет некую священную цель — то древнее заблуждение ныне обратилось в прах.",
    endingSentence2: "Она возвышается лишь как чистое воплощение человеческой воли.",

    npc_daedalus: "Даэдал",
    npc_salesman: "Торговец",
    npc_dummy: "Чудачка",

    dialogueIntro: "Зайду в мастерскую и попробую сделать крылья прочнее. Заодно и по городу пройдусь.",
    dialogueNeedWings: "Сперва мне нужны новые крылья!",
    dialogueNpc1_1: "Привет, ремесленник, как дела?",
    dialogueNpc1_2: "Могло быть и лучше",
    dialogueNpc1_3: "Ты еще молод, но не забудь вернуться домой из этой своей башни",
    dialogueNpc1_4: "Береги себя",
    dialogueNpc2_1: "Твои крылья смешные",
    dialogueNpc2_2: "С лучшими крыльями ты можешь УДЕРЖИВАТЬ пробел, чтобы лететь выше!",
    dialogueNpc2_3: "Что я только что сказала? Забудь. Кажется, я видела фиолетовый куб в лесу",
    dialogueBum_1: "*Ик!* ... *Ик!*",
    dialogueBum_2: "От него несёт перегаром...",

    tutorialTitle: "ОБУЧЕНИЕ",
    tutorialCityTitle: "В городе",
    tutorialCityText: "A / D — Перемещение<br/>E — Взаимодействие",
    tutorialCityTextTouch: "◄ / ► — Перемещение<br/>ДЕЙСТВИЕ — Разговор и Магазины",
    tutorialTowerTitle: "В башне",
    tutorialTowerText: "ПРОБЕЛ — Взмах крыльев<br/>A / D — Маневрирование",
    tutorialTowerTextTouch: "ВЗМАХ — Взлет выше<br/>◄ / ► — Маневрирование",
    tutorialBtn: "ПОНЯТНО!",

    introSlide1: "Игра от Dahaton и Coyz<br/><br/>Музыка:<br/>A Long Story — Damiano Baldoni",
    introSlide2: "Легенда гласит, что люди прошлого построили башню.",
    introSlide3: "Башню настолько высокую, что никто не видел её вершины.",
    introSlide4: "Её предназначение неизвестно и по сей день.",
    introSlide5: "И в каждый последующий день.",
    introSlide6: "По крайней мере, так говорят.",

    creditsTitle: "АВТОРЫ",
    gameCreatedBy: "Создатели игры:",
    authorsList: "Dahaton и Coyz",
    musicBy: "Музыка:",
    musicianName: "Damiano Baldoni",
    specialThanks: "Особая благодарность тестировщикам и игрокам!",
    
    lockedRecipe: "Заблокировано - достигните высшего уровня в Башне",
    climbToDiscover: "Поднимайтесь на Башню, чтобы открыть!",
    shopHint: "Нажмите, чтобы купить / продать. [E] - Выход",

    item_fabric1: "Ткань I", item_fabric2: "Ткань II", item_fabric3: "Ткань III",
    item_steel1: "Сталь I", item_steel2: "Сталь II", item_steel3: "Сталь III",
    item_wood1: "Дерево I", item_wood2: "Дерево II", item_wood3: "Дерево III",
    item_wax: "Воск", item_coin: "Монета",

    wing_SteelWings: "Стальные крылья",
    wing_DurableSteelWings: "Прочные стальные крылья",
    wing_SuperSteelWings: "Суперстальные крылья",
    wing_SuperDurableSteelWings: "Прочные суперстальные крылья",
    wing_EnchantedWings: "Зачарованные крылья",
    wing_DurableEnchantedWings: "Прочные зачарованные крылья",
    wing_SuperEnchantedWings: "Суперзачарованные крылья",
    wing_SuperDurableEnchantedWings: "Прочные суперзачарованные крылья",
    wing_MythrilWings: "Мифриловые крылья",
    wing_DurableMythrilWings: "Прочные мифриловые крылья",
    wing_WaxWings: "Восковые крылья"
  }
};

export function t(key) {
  const lang = state.language || 'en';
  const dict = TRANSLATIONS[lang] || TRANSLATIONS['en'];
  return dict[key] || TRANSLATIONS['en'][key] || key;
}